"""
Student information for this assignment:

Replace Alan Kurian Abraham with your name.
On my/our honor, Alan Kurian Abraham and n/a, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: aka3358
UT EID 2:
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    sub = ''
    valid_sub = []
    max_len = 0
    for i in range(len(s)):
        for j in range(i, len(s)):
            if s[j] not in sub:
                sub += s[j]
            else:
                valid_sub.append(sub)
        for i, substring in enumerate(valid_sub):
            if len(substring) > max_len:
                max_len = len(substring)
    return max_len

def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    sub = ''
    max_len = 0
    for i in range(len(s)):
        for j in range(i, len(s)):
            if s[j] not in sub:
                sub += s[j]
            else:
                break
        if len(sub) > max_len:
            max_len = len(sub)
        sub = ''
    return max_len

def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    if not s:
        return 0
    char_position = {}
    max_length = 0
    start = 0
    for end, _ in enumerate(s):
        if s[end] in char_position and char_position[s[end]] >= start:
            start = char_position[s[end]] + 1
        else:
            max_length = max(max_length, end - start + 1)
        char_position[s[end]] = end
    return max_length
