"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Alan Kurian Abraham and n/a, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: aka3358
UT EID 2: n/a
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        if(coeff == 0):
            return
        temp = self.head
        if temp is None:
            self.head = Node(coeff, exp)
            return
        if temp.exp == exp:
                temp.coeff = temp.coeff+coeff
                if temp.coeff == 0:
                    self.head = self.head.next
                return
        if temp.exp < exp:
                temp2 = temp
                self.head = Node(coeff, exp)
                self.head.next = temp2
                return
        while temp is not None:
            if not temp.next or temp.next.exp < exp:
                temp2 = temp.next
                temp.next = Node(coeff, exp)
                temp.next.next = temp2
                break
            if temp.next.exp == exp:
                temp.next.coeff = temp.next.coeff+coeff
                if temp.next.coeff == 0:
                    temp.next = temp.next.next
                break
            
            temp = temp.next

            

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        ret = LinkedList()
        temp2 = self.head
        while temp2 is not None:
            ret.insert_term(temp2.coeff, temp2.exp)
            temp2 = temp2.next
        temp2 = p.head
        while temp2 is not None:
            ret.insert_term(temp2.coeff, temp2.exp)
            temp2 = temp2.next
        return ret

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        ret = LinkedList()
        temp2 = self.head
        while temp2 is not None:
            temp3 = p.head
            while temp3 is not None:
                ret.insert_term(temp3.coeff*temp2.coeff, temp3.exp+ temp2.exp)
                temp3 = temp3.next
            temp2 = temp2.next
        return ret


    # Return a string representation of the polynomial.
    def __str__(self):
        temp = self.head
        ret = ""
        while temp is not None:
            ret += "(" + str(temp.coeff) + ", " + str(temp.exp) + ")"
            if temp.next is not None:
                ret += " + "
            temp = temp.next
        return ret


def main():
    # read data from stdin (terminal/file) using input() and create polynomial p
    num = int(input())
    p = LinkedList()
    for _ in range(num):
        p.insert_term(input(), input())
    # read data from stdin (terminal/file) using input() and create polynomial q
    num = int(input())
    q = LinkedList()
    for _ in range(num):
        q.insert_term(input(), input())
    # get sum of p and q as a new linked list and print sum
    print(str(p.add(q)))
    # get product of p and q as a new linked list and print product
    print(str(p.mult(q)))


if __name__ == "__main__":
    main()
